version: '3.8'

services:

  etl:
    build: etl
    depends_on:
      - db
      - elastic_search
      - redis
    env_file:
      - ./.env
    networks:
      - etl_api_network

  api:
    build: src
    depends_on:
      - etl
    env_file:
      - ./.env
    networks:
      - etl_api_network
  
  db:
    image: postgres:latest
    restart: always
    volumes:
      - posgresql_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - etl_api_network

  elastic_search:
    image: ghcr.io/yp-middle-python-24/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
    ports:
      - "9200:9200"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - etl_api_network

  redis:
    image: redis:latest
    expose:
      - "6379"
    env_file:
      - ./.env
    networks:
      - etl_api_network
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    env_file:
      - ./.env
    networks:
      - etl_api_network

volumes:
  posgresql_data:

networks:
  etl_api_network:
